name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # her 12 saatte bir çalışır
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: farukkamcici
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit outputs
        run: |
          git config --local user.name "github-actions"
          git add dist/
          git commit -m "Update snake"
          git push
